# **20260704-토요실습1**

### 먼저 전체를 출력

In [28]:
import matplotlib.pyplot as plt       # 맷플롯리브 시각화
import pandas as pd                   # 판다스 데이터분석
import numpy as np                    # 넘파이 수학계산
                                      # 버스 스테이션이란 함수에, 시트 네임을 버스 스테이션으로 한 서울 트래픽 xlsx 파일을 읽을 결과를 저장한다. 변수이다.
bus_station=pd.read_excel('seoul_traffic_202605.xlsx', sheet_name='bus_station')

In [8]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

bus_station=pd.read_excel('seoul_traffic_202605.xlsx', sheet_name='bus_station')
bus_station

,사용월,노선ID,노선번호,노선명,버스정류장ID,버스정류장명,승차승객수,하차승객수
0,2026-05,11110897,0017,0017번(용산차고지~신용산역3번출구),8503228,용산차고지(가상),25,5
1,2026-05,11110897,0017,0017번(용산차고지~신용산역3번출구),8503189,신용산지하차도,735,21
2,2026-05,11110897,0017,0017번(용산차고지~신용산역3번출구),72992,용산역,"22,519",352
3,2026-05,11110897,0017,0017번(용산차고지~신용산역3번출구),72314,용산푸르지오써밋,"1,782",488
4,2026-05,11110897,0017,0017번(용산차고지~신용산역3번출구),72993,한강대교북단,"7,261","1,998"
...,...,...,...,...,...,...,...,...
41995,2026-05,92000001,한강버스01,한강버스01(마곡~잠실),8503213,압구정,"4,899","3,375"
41996,2026-05,92000001,한강버스01,한강버스01(마곡~잠실),8503214,옥수,"5,891","3,566"
41997,2026-05,92000001,한강버스01,한강버스01(마곡~잠실),8503414,성수,4,4
41998,2026-05,92000001,한강버스01,한강버스01(마곡~잠실),8503215,뚝섬,"8,736","6,459"
41999,2026-05,92000001,한강버스01,한강버스01(마곡~잠실),8503216,잠실,"9,667","12,434"

### 선택 출력

In [7]:
bus_station[['버스정류장ID', '승차승객수']] # 두 가지 열만 선택

       버스정류장ID   승차승객수
0      8503228      25
1      8503189     735
2        72992  22,519
3        72314   1,782
4        72993   7,261
...        ...     ...
41995  8503213   4,899
41996  8503214   5,891
41997  8503414       4
41998  8503215   8,736
41999  8503216   9,667

[42000 rows x 2 columns]

In [9]:
bus_station[['노선번호', '노선명']] # 두 가지 열만 선택

         노선번호                    노선명
0        0017  0017번(용산차고지~신용산역3번출구)
1        0017  0017번(용산차고지~신용산역3번출구)
2        0017  0017번(용산차고지~신용산역3번출구)
3        0017  0017번(용산차고지~신용산역3번출구)
4        0017  0017번(용산차고지~신용산역3번출구)
...       ...                    ...
41995  한강버스01          한강버스01(마곡~잠실)
41996  한강버스01          한강버스01(마곡~잠실)
41997  한강버스01          한강버스01(마곡~잠실)
41998  한강버스01          한강버스01(마곡~잠실)
41999  한강버스01          한강버스01(마곡~잠실)

[42000 rows x 2 columns]

In [14]:
bus_station[['노선번호','노선명','버스정류장ID','버스정류장명','승차승객수','하차승객수']] # 출력하고픈 열들을 지정

         노선번호                    노선명  버스정류장ID     버스정류장명   승차승객수   하차승객수
0        0017  0017번(용산차고지~신용산역3번출구)  8503228  용산차고지(가상)      25       5
1        0017  0017번(용산차고지~신용산역3번출구)  8503189    신용산지하차도     735      21
2        0017  0017번(용산차고지~신용산역3번출구)    72992        용산역  22,519     352
3        0017  0017번(용산차고지~신용산역3번출구)    72314   용산푸르지오써밋   1,782     488
4        0017  0017번(용산차고지~신용산역3번출구)    72993     한강대교북단   7,261   1,998
...       ...                    ...      ...        ...     ...     ...
41995  한강버스01          한강버스01(마곡~잠실)  8503213        압구정   4,899   3,375
41996  한강버스01          한강버스01(마곡~잠실)  8503214         옥수   5,891   3,566
41997  한강버스01          한강버스01(마곡~잠실)  8503414         성수       4       4
41998  한강버스01          한강버스01(마곡~잠실)  8503215         뚝섬   8,736   6,459
41999  한강버스01          한강버스01(마곡~잠실)  8503216         잠실   9,667  12,434

[42000 rows x 6 columns]

In [12]:
bus_station[['노선번호','노선명','버스정류장ID','버스정류장명','승차승객수','하차승객수']].head(9)   # 상위 9 라인만 출력

   노선번호                    노선명  버스정류장ID           버스정류장명   승차승객수  하차승객수
0  0017  0017번(용산차고지~신용산역3번출구)  8503228        용산차고지(가상)      25      5
1  0017  0017번(용산차고지~신용산역3번출구)  8503189          신용산지하차도     735     21
2  0017  0017번(용산차고지~신용산역3번출구)    72992              용산역  22,519    352
3  0017  0017번(용산차고지~신용산역3번출구)    72314         용산푸르지오써밋   1,782    488
4  0017  0017번(용산차고지~신용산역3번출구)    72993           한강대교북단   7,261  1,998
5  0017  0017번(용산차고지~신용산역3번출구)    72994          서부이촌동입구   2,703  8,094
6  0017  0017번(용산차고지~신용산역3번출구)    72995  이촌2동대림아파트.새남터성지   1,602  7,579
7  0017  0017번(용산차고지~신용산역3번출구)    72996         이촌2동주민센터   1,605  5,088
8  0017  0017번(용산차고지~신용산역3번출구)    72997      이촌로입구.성촌공원앞     389  1,298

### 이름(Label)으로 접근하느냐(loc), 위치를 나타내는 정수(Integer)로 접근하느냐(iloc)

In [13]:
bus_station.iloc[1:5]

,사용월,노선ID,노선번호,노선명,버스정류장ID,버스정류장명,승차승객수,하차승객수
1,2026-05,11110897,0017,0017번(용산차고지~신용산역3번출구),8503189,신용산지하차도,735,21
2,2026-05,11110897,0017,0017번(용산차고지~신용산역3번출구),72992,용산역,"22,519",352
3,2026-05,11110897,0017,0017번(용산차고지~신용산역3번출구),72314,용산푸르지오써밋,"1,782",488
4,2026-05,11110897,0017,0017번(용산차고지~신용산역3번출구),72993,한강대교북단,"7,261","1,998"

### loc iloc practice

In [16]:
bus_station.iloc[1]

사용월                      2026-05
노선ID                    11110897
노선번호                        0017
노선명        0017번(용산차고지~신용산역3번출구)
버스정류장ID                  8503189
버스정류장명                   신용산지하차도
승차승객수                        735
하차승객수                         21
Name: 1, dtype: object

In [19]:
bus_station.iloc[[1,2]]     # 복수는 두개의 대괄호

,사용월,노선ID,노선번호,노선명,버스정류장ID,버스정류장명,승차승객수,하차승객수
1,2026-05,11110897,0017,0017번(용산차고지~신용산역3번출구),8503189,신용산지하차도,735,21
2,2026-05,11110897,0017,0017번(용산차고지~신용산역3번출구),72992,용산역,"22,519",352

In [23]:
bus_station.loc[0:3, '버스정류장명':'하차승객수']        # 버스정류장명  부터 하차승객수 사이의(포함) 모든 열을 선택하며, 0번부터 3번째 행까지 출력한다.

      버스정류장명   승차승객수 하차승객수
0  용산차고지(가상)      25     5
1    신용산지하차도     735    21
2        용산역  22,519   352
3   용산푸르지오써밋   1,782   488

In [34]:
bus_station.loc[0:4, '버스정류장명':'하차승객수']

      버스정류장명   승차승객수  하차승객수
0  용산차고지(가상)      25      5
1    신용산지하차도     735     21
2        용산역  22,519    352
3   용산푸르지오써밋   1,782    488
4     한강대교북단   7,261  1,998

In [ ]:
bus_station