# **20260705-일요실습1**

### 시작 -

In [1]:
import matplotlib.pyplot as plt       # 맷플롯리브 시각화
import pandas as pd                   # 판다스 데이터분석
import numpy as np                    # 넘파이 수학계산

### 다시한번 서울지하철 - **seoul_traffic_202605.xlsx** (여기부터 이어서 시작)

In [5]:
df_line=pd.read_excel('seoul_traffic_202605.xlsx', sheet_name='subway_line_station')
df_line

         사용월  호선명   역ID      지하철역    승차승객수    하차승객수
0    2026-05  1호선   150       서울역  2449533  2405533
1    2026-05  1호선   151        시청   783572   790172
2    2026-05  1호선   152        종각  1202972  1157214
3    2026-05  1호선   153      종로3가   835118   745726
4    2026-05  1호선   154      종로5가   747033   725378
..       ...  ...   ...       ...      ...      ...
615  2026-05  신림선  4407        당곡   145646   138721
616  2026-05  신림선  4408        신림    72092    85438
617  2026-05  신림선  4409        서원   108743    96180
618  2026-05  신림선  4410   서울대벤처타운   309687   283165
619  2026-05  신림선  4411  관악산(서울대)   119147   117143

[620 rows x 6 columns]

In [3]:
df_line=pd.read_excel('seoul_traffic_202605.xlsx', sheet_name='subway_line_station')
df_line=df_line[['사용월','호선명','역ID','지하철역','승차승객수','하차승객수']]         
df_line                                                                                #질문을 하니 교수님께서 직접 오셔서 ddf_line 새 정의를 해주셨다.

         사용월  호선명   역ID      지하철역    승차승객수    하차승객수
0    2026-05  1호선   150       서울역  2449533  2405533
1    2026-05  1호선   151        시청   783572   790172
2    2026-05  1호선   152        종각  1202972  1157214
3    2026-05  1호선   153      종로3가   835118   745726
4    2026-05  1호선   154      종로5가   747033   725378
..       ...  ...   ...       ...      ...      ...
615  2026-05  신림선  4407        당곡   145646   138721
616  2026-05  신림선  4408        신림    72092    85438
617  2026-05  신림선  4409        서원   108743    96180
618  2026-05  신림선  4410   서울대벤처타운   309687   283165
619  2026-05  신림선  4411  관악산(서울대)   119147   117143

[620 rows x 6 columns]

In [9]:
df_line['총승하차승객수']=df_line['승차승객수']+df_line['하차승객수']              #df_line 에 없는걸 선언한건 만들겠다는 뜻
df_line                                                                           # 이제 출력한다.

         사용월  호선명   역ID      지하철역    승차승객수    하차승객수  총승하차승객수
0    2026-05  1호선   150       서울역  2449533  2405533  4855066
1    2026-05  1호선   151        시청   783572   790172  1573744
2    2026-05  1호선   152        종각  1202972  1157214  2360186
3    2026-05  1호선   153      종로3가   835118   745726  1580844
4    2026-05  1호선   154      종로5가   747033   725378  1472411
..       ...  ...   ...       ...      ...      ...      ...
615  2026-05  신림선  4407        당곡   145646   138721   284367
616  2026-05  신림선  4408        신림    72092    85438   157530
617  2026-05  신림선  4409        서원   108743    96180   204923
618  2026-05  신림선  4410   서울대벤처타운   309687   283165   592852
619  2026-05  신림선  4411  관악산(서울대)   119147   117143   236290

[620 rows x 7 columns]

#### 총승하차승객수를 호선명을 기준으로 그룹바이

In [11]:
df_line[['호선명','총승하차승객수']].groupby('호선명').sum().head(9)

      총승하차승객수
호선명
1호선  16977364
2호선  87787733
3호선  33326606
4호선  34133290
5호선  40983496
6호선  21733007
7호선  36409565
8호선  12825792
9호선  17664094